language: python
python:
  - "2.7"
env:
  - TOXENV=py27
  - TOXENV=pep8
  - TOXENV=docs 

install:
  - pip install tox
  - pip install coveralls 
script:
  - tox 

after_success:
  coveralls --verbose
